-- =========================================================================
-- Use Case: S001 Initialization of System Roles and Base Test Accounts
-- Author: 钮培源
-- Date: 2026-07-18 (revised)
-- Is Repeatable: Yes 
-- =========================================================================

-- Deprecated: Wipe existing seed data for safe re-runs 
-- TRUNCATE TABLE USER_ROLES;
-- DELETE FROM EMPLOYEES;
-- DELETE FROM ROLES;
-- DELETE FROM DEPARTMENTS_TRAINING;
-- COMMIT;

WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET NLS_LENGTH_SEMANTICS = CHAR;

-- Four fixed roles
INSERT INTO ROLES (ROLE_CODE, ROLE_NAME)
SELECT 'ADMIN', '系统管理员' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE ROLE_CODE = 'ADMIN');

INSERT INTO ROLES (ROLE_CODE, ROLE_NAME)
SELECT 'EMPLOYEE', '普通员工' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE ROLE_CODE = 'EMPLOYEE');

INSERT INTO ROLES (ROLE_CODE, ROLE_NAME)
SELECT 'MANAGER', '部门主管' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE ROLE_CODE = 'MANAGER');

INSERT INTO ROLES (ROLE_CODE, ROLE_NAME)
SELECT 'HR', 'HR管理员' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM ROLES WHERE ROLE_CODE = 'HR');

-- Control-center department
INSERT INTO DEPARTMENTS_TRAINING (DEPT_NAME, BUDGET_YEAR, ANNUAL_BUDGET, USED_BUDGET)
SELECT '公司外训控制中心', 2026, 500000.00, 0.00 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '公司外训控制中心');

-- Four role-test accounts.
-- The plain-text password for these accounts is simulated as Password2026!, 
-- which maps to a standard 60-character BCrypt tracking hash.

INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, EMAIL, PHONE, STATUS)
SELECT 'admin', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '系统超级管理员',
       (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '公司外训控制中心'),
       'IT系统架构师', 'admin@training2026.com', '13800000001', 'ACTIVE'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEES WHERE LOGIN_NAME = 'admin');

INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, EMAIL, PHONE, STATUS)
SELECT 'employee', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '测试普通员工',
       (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '公司外训控制中心'),
       '软件开发工程师', 'employee@training2026.com', '13800000002', 'ACTIVE'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEES WHERE LOGIN_NAME = 'employee');

INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, EMAIL, PHONE, STATUS)
SELECT 'manager', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '测试部门主管',
       (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '公司外训控制中心'),
       '研发部经理', 'manager@training2026.com', '13800000003', 'ACTIVE'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEES WHERE LOGIN_NAME = 'manager');

INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, EMAIL, PHONE, STATUS)
SELECT 'hr', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '测试HR专员',
       (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '公司外训控制中心'),
       '培训发展主管', 'hr@training2026.com', '13800000004', 'ACTIVE'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEES WHERE LOGIN_NAME = 'hr');

-- Role bindings
INSERT INTO USER_ROLES (EMP_ID, ROLE_ID)
SELECT e.EMP_ID, r.ROLE_ID FROM EMPLOYEES e, ROLES r
WHERE e.LOGIN_NAME = 'admin' AND r.ROLE_CODE = 'ADMIN'
  AND NOT EXISTS (SELECT 1 FROM USER_ROLES ur WHERE ur.EMP_ID = e.EMP_ID AND ur.ROLE_ID = r.ROLE_ID);

INSERT INTO USER_ROLES (EMP_ID, ROLE_ID)
SELECT e.EMP_ID, r.ROLE_ID FROM EMPLOYEES e, ROLES r
WHERE e.LOGIN_NAME = 'employee' AND r.ROLE_CODE = 'EMPLOYEE'
  AND NOT EXISTS (SELECT 1 FROM USER_ROLES ur WHERE ur.EMP_ID = e.EMP_ID AND ur.ROLE_ID = r.ROLE_ID);

INSERT INTO USER_ROLES (EMP_ID, ROLE_ID)
SELECT e.EMP_ID, r.ROLE_ID FROM EMPLOYEES e, ROLES r
WHERE e.LOGIN_NAME = 'manager' AND r.ROLE_CODE = 'MANAGER'
  AND NOT EXISTS (SELECT 1 FROM USER_ROLES ur WHERE ur.EMP_ID = e.EMP_ID AND ur.ROLE_ID = r.ROLE_ID);

INSERT INTO USER_ROLES (EMP_ID, ROLE_ID)
SELECT e.EMP_ID, r.ROLE_ID FROM EMPLOYEES e, ROLES r
WHERE e.LOGIN_NAME = 'hr' AND r.ROLE_CODE = 'HR'
  AND NOT EXISTS (SELECT 1 FROM USER_ROLES ur WHERE ur.EMP_ID = e.EMP_ID AND ur.ROLE_ID = r.ROLE_ID);

COMMIT;

