-- =========================================================================
-- Use Case: S001 Initialization of System Roles and Base Test Accounts
-- Author: 钮培源 
-- Date: 2026-07-15
-- Is Repeatable: Yes (Includes cleanup for idempotency), but NOT RECOMMENDED 
-- =========================================================================

-- Wipe existing seed data for safe re-runs 
TRUNCATE TABLE USER_ROLES;
DELETE FROM EMPLOYEES;
DELETE FROM ROLES;
DELETE FROM DEPARTMENTS_TRAINING;
COMMIT;


INSERT INTO ROLES (ROLE_CODE, ROLE_NAME) VALUES ('ADMIN', '系统管理员');
INSERT INTO ROLES (ROLE_CODE, ROLE_NAME) VALUES ('EMPLOYEE', '普通员工');
INSERT INTO ROLES (ROLE_CODE, ROLE_NAME) VALUES ('MANAGER', '部门主管');
INSERT INTO ROLES (ROLE_CODE, ROLE_NAME) VALUES ('HR', 'HR管理员');

INSERT INTO DEPARTMENTS_TRAINING (DEPT_NAME, BUDGET_YEAR, ANNUAL_BUDGET, USED_BUDGET)
VALUES ('公司外训控制中心', 2026, 500000.00, 0.00);


INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, EMAIL, PHONE, STATUS)
VALUES ('admin', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '系统超级管理员', 
        (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '公司外训控制中心'), 
        'IT系统架构师', 'admin@training2026.com', '13800000001', 'ACTIVE');

INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, EMAIL, PHONE, STATUS)
VALUES ('employee', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '测试普通员工', 
        (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '公司外训控制中心'), 
        '软件开发工程师', 'employee@training2026.com', '13800000002', 'ACTIVE');

INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, EMAIL, PHONE, STATUS)
VALUES ('manager', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '测试部门主管', 
        (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '公司外训控制中心'), 
        '研发部经理', 'manager@training2026.com', '13800000003', 'ACTIVE');

INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, EMAIL, PHONE, STATUS)
VALUES ('hr', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '测试HR专员', 
        (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '公司外训控制中心'), 
        '培训发展主管', 'hr@training2026.com', '13800000004', 'ACTIVE');

INSERT INTO USER_ROLES (EMP_ID, ROLE_ID)
VALUES ((SELECT EMP_ID FROM EMPLOYEES WHERE LOGIN_NAME = 'admin'), (SELECT ROLE_ID FROM ROLES WHERE ROLE_CODE = 'ADMIN'));

INSERT INTO USER_ROLES (EMP_ID, ROLE_ID)
VALUES ((SELECT EMP_ID FROM EMPLOYEES WHERE LOGIN_NAME = 'employee'), (SELECT ROLE_ID FROM ROLES WHERE ROLE_CODE = 'EMPLOYEE'));

INSERT INTO USER_ROLES (EMP_ID, ROLE_ID)
VALUES ((SELECT EMP_ID FROM EMPLOYEES WHERE LOGIN_NAME = 'manager'), (SELECT ROLE_ID FROM ROLES WHERE ROLE_CODE = 'MANAGER'));

INSERT INTO USER_ROLES (EMP_ID, ROLE_ID)
VALUES ((SELECT EMP_ID FROM EMPLOYEES WHERE LOGIN_NAME = 'hr'), (SELECT ROLE_ID FROM ROLES WHERE ROLE_CODE = 'HR'));

COMMIT;
