-- =========================================================================
-- Use Case: S002 Core Organizational and Course Catalog Data
-- Author: 钮培源
-- Date: 2026-07-16
-- =========================================================================

INSERT INTO DEPARTMENTS_TRAINING (DEPT_NAME, BUDGET_YEAR, ANNUAL_BUDGET, USED_BUDGET) 
VALUES ('研发部', 2026, 300000.00, 0.00);

INSERT INTO DEPARTMENTS_TRAINING (DEPT_NAME, BUDGET_YEAR, ANNUAL_BUDGET, USED_BUDGET) 
VALUES ('产品部', 2026, 200000.00, 0.00);

INSERT INTO DEPARTMENTS_TRAINING (DEPT_NAME, BUDGET_YEAR, ANNUAL_BUDGET, USED_BUDGET) 
VALUES ('市场部', 2026, 250000.00, 0.00);


-- R&D Employees
INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, STATUS)
VALUES ('dev01', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '张后端', 
        (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '研发部'), '后端开发', 'ACTIVE');

INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, STATUS)
VALUES ('dev02', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '李前端', 
        (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '研发部'), '前端开发', 'ACTIVE');

INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, STATUS)
VALUES ('dev03', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '王测试', 
        (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '研发部'), '测试工程师', 'ACTIVE');

-- Product Employees
INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, STATUS)
VALUES ('prod01', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '赵产品', 
        (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '产品部'), '产品经理', 'ACTIVE');

INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, STATUS)
VALUES ('prod02', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '孙交互', 
        (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '产品部'), 'UI设计师', 'ACTIVE');

-- Marketing Employees
INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, STATUS)
VALUES ('mkt01', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '周营销', 
        (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '市场部'), '营销策划', 'ACTIVE');

INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, STATUS)
VALUES ('mkt02', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '吴销售', 
        (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '市场部'), '大客户销售', 'ACTIVE');

INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, STATUS)
VALUES ('mkt03', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '郑运营', 
        (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '市场部'), '活动运营', 'ACTIVE');

INSERT INTO TRAINERS (TRAINER_NAME, TITLE, COMPANY, STAR_LEVEL, IS_INTERNAL)
VALUES ('陈技术', '高级架构师', '内部讲师', 4.5, 'Y');

INSERT INTO TRAINERS (TRAINER_NAME, TITLE, COMPANY, STAR_LEVEL, IS_INTERNAL)
VALUES ('林外聘', '特约敏捷教练', '敏捷咨询公司', 5.0, 'N');

INSERT INTO TRAINERS (TRAINER_NAME, TITLE, COMPANY, STAR_LEVEL, IS_INTERNAL)
VALUES ('郭产品', '产品总监', '内部讲师', 4.0, 'Y');


INSERT INTO TRAINING_COURSES (COURSE_NAME, COURSE_TYPE, DURATION_HOURS, TRAINER_ID, MAX_STUDENTS, START_AT, END_AT, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID)
VALUES ('2026 微服务架构演进', '技术培训', 8.0, 
        (SELECT TRAINER_ID FROM TRAINERS WHERE TRAINER_NAME = '陈技术'), 
        30, TO_TIMESTAMP('2026-08-10 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-08-10 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
        '总部第一会议室', 'DRAFT', 5000.00, (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '研发部'));

INSERT INTO TRAINING_COURSES (COURSE_NAME, COURSE_TYPE, DURATION_HOURS, TRAINER_ID, MAX_STUDENTS, START_AT, END_AT, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID)
VALUES ('C# Web API 最佳实践', '技术培训', 4.0, 
        (SELECT TRAINER_ID FROM TRAINERS WHERE TRAINER_NAME = '陈技术'), 
        40, TO_TIMESTAMP('2026-08-15 13:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-08-15 17:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
        '总部第二会议室', 'DRAFT', 2000.00, (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '研发部'));

INSERT INTO TRAINING_COURSES (COURSE_NAME, COURSE_TYPE, DURATION_HOURS, TRAINER_ID, MAX_STUDENTS, START_AT, END_AT, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID)
VALUES ('2026 敏捷项目管理工作坊', '管理培训', 16.0, 
        (SELECT TRAINER_ID FROM TRAINERS WHERE TRAINER_NAME = '林外聘'), 
        20, TO_TIMESTAMP('2026-09-01 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-09-02 18:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
        '外部培训中心', 'DRAFT', 25000.00, (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '研发部'));

INSERT INTO TRAINING_COURSES (COURSE_NAME, COURSE_TYPE, DURATION_HOURS, TRAINER_ID, MAX_STUDENTS, START_AT, END_AT, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID)
VALUES ('用户体验驱动的产品设计', '产品培训', 6.0, 
        (SELECT TRAINER_ID FROM TRAINERS WHERE TRAINER_NAME = '郭产品'), 
        25, TO_TIMESTAMP('2026-09-20 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-09-20 17:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
        '总部第三会议室', 'DRAFT', 3000.00, (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '产品部'));

INSERT INTO TRAINING_COURSES (COURSE_NAME, COURSE_TYPE, DURATION_HOURS, TRAINER_ID, MAX_STUDENTS, START_AT, END_AT, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID)
VALUES ('2026 B2B 销售实战技巧', '营销培训', 12.0, 
        (SELECT TRAINER_ID FROM TRAINERS WHERE TRAINER_NAME = '林外聘'), 
        50, TO_TIMESTAMP('2026-10-10 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2026-10-11 12:00:00', 'YYYY-MM-DD HH24:MI:SS'), 
        '公司大会堂', 'DRAFT', 15000.00, (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '市场部'));

COMMIT;


-- Verified with:
-- check total table cnts
-- SELECT 
--     (SELECT COUNT(*) FROM DEPARTMENTS_TRAINING) AS DEPT_COUNT,
--     (SELECT COUNT(*) FROM EMPLOYEES) AS EMP_COUNT,
--     (SELECT COUNT(*) FROM TRAINERS) AS TRAINER_COUNT,
--     (SELECT COUNT(*) FROM TRAINING_COURSES) AS COURSE_COUNT
-- FROM DUAL;

-- verify foreign key linkage
-- SELECT 
--     c.COURSE_NAME, 
--     t.TRAINER_NAME, 
--     d.DEPT_NAME, 
--     c.COURSE_STATUS
-- FROM TRAINING_COURSES c
-- JOIN TRAINERS t ON c.TRAINER_ID = t.TRAINER_ID
-- JOIN DEPARTMENTS_TRAINING d ON c.DEPT_ID = d.DEPT_ID;
