-- =========================================================================
-- Use Case: S002 Core Organizational and Course Catalog Data
-- Author: 钮培源
-- Date: 2026-07-20 (revised)
-- Is Repeatable: Yes
-- =========================================================================

WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET NLS_LENGTH_SEMANTICS = CHAR;

-- Departments
INSERT INTO DEPARTMENTS_TRAINING (DEPT_NAME, BUDGET_YEAR, ANNUAL_BUDGET, USED_BUDGET)
SELECT '研发部', 2026, 300000.00, 0.00 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '研发部');

INSERT INTO DEPARTMENTS_TRAINING (DEPT_NAME, BUDGET_YEAR, ANNUAL_BUDGET, USED_BUDGET)
SELECT '产品部', 2026, 200000.00, 0.00 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '产品部');

INSERT INTO DEPARTMENTS_TRAINING (DEPT_NAME, BUDGET_YEAR, ANNUAL_BUDGET, USED_BUDGET)
SELECT '市场部', 2026, 250000.00, 0.00 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '市场部');

-- R&D staff (dev03 remains the QA engineer)
INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, STATUS)
SELECT 'dev01', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '张后端',
       (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '研发部'), '后端开发', 'ACTIVE'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEES WHERE LOGIN_NAME = 'dev01');

INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, STATUS)
SELECT 'dev02', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '李前端',
       (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '研发部'), '前端开发', 'ACTIVE'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEES WHERE LOGIN_NAME = 'dev02');

INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, STATUS)
SELECT 'dev03', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '王测试',
       (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '研发部'), '测试工程师', 'ACTIVE'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEES WHERE LOGIN_NAME = 'dev03');

-- Dedicated R&D-department manager (added for same-department approval)
INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, STATUS)
SELECT 'rdmgr', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '刘研发',
       (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '研发部'), '研发部经理', 'ACTIVE'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEES WHERE LOGIN_NAME = 'rdmgr');

-- Product staff
INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, STATUS)
SELECT 'prod01', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '赵产品',
       (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '产品部'), '产品经理', 'ACTIVE'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEES WHERE LOGIN_NAME = 'prod01');

INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, STATUS)
SELECT 'prod02', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '孙交互',
       (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '产品部'), 'UI设计师', 'ACTIVE'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEES WHERE LOGIN_NAME = 'prod02');

-- Marketing staff
INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, STATUS)
SELECT 'mkt01', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '周营销',
       (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '市场部'), '营销策划', 'ACTIVE'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEES WHERE LOGIN_NAME = 'mkt01');

INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, STATUS)
SELECT 'mkt02', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '吴销售',
       (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '市场部'), '大客户销售', 'ACTIVE'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEES WHERE LOGIN_NAME = 'mkt02');

INSERT INTO EMPLOYEES (LOGIN_NAME, PASSWORD_HASH, EMP_NAME, DEPT_ID, POSITION, STATUS)
SELECT 'mkt03', '$2a$11$K3vYV6WpLpC9aE8uXgR7eO8bH6zZ4vV2xX1yY3zZ5wW6vV7uU8tTs', '郑运营',
       (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '市场部'), '活动运营', 'ACTIVE'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEES WHERE LOGIN_NAME = 'mkt03');

-- Role bindings
-- 8 base staff -> EMPLOYEE
INSERT INTO USER_ROLES (EMP_ID, ROLE_ID)
SELECT e.EMP_ID, r.ROLE_ID FROM EMPLOYEES e, ROLES r
WHERE e.LOGIN_NAME IN ('dev01', 'dev02', 'dev03', 'prod01', 'prod02', 'mkt01', 'mkt02', 'mkt03')
  AND r.ROLE_CODE = 'EMPLOYEE'
  AND NOT EXISTS (SELECT 1 FROM USER_ROLES ur WHERE ur.EMP_ID = e.EMP_ID AND ur.ROLE_ID = r.ROLE_ID);

-- rdmgr -> MANAGER
INSERT INTO USER_ROLES (EMP_ID, ROLE_ID)
SELECT e.EMP_ID, r.ROLE_ID FROM EMPLOYEES e, ROLES r
WHERE e.LOGIN_NAME = 'rdmgr' AND r.ROLE_CODE = 'MANAGER'
  AND NOT EXISTS (SELECT 1 FROM USER_ROLES ur WHERE ur.EMP_ID = e.EMP_ID AND ur.ROLE_ID = r.ROLE_ID);

-- --- Trainers -------------------------------------------------------------
INSERT INTO TRAINERS (TRAINER_NAME, TITLE, COMPANY, STAR_LEVEL, IS_INTERNAL)
SELECT '陈技术', '高级架构师', '内部讲师', 4.5, 'Y' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TRAINERS WHERE TRAINER_NAME = '陈技术');

INSERT INTO TRAINERS (TRAINER_NAME, TITLE, COMPANY, STAR_LEVEL, IS_INTERNAL)
SELECT '林外聘', '特约敏捷教练', '敏捷咨询公司', 5.0, 'N' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TRAINERS WHERE TRAINER_NAME = '林外聘');

INSERT INTO TRAINERS (TRAINER_NAME, TITLE, COMPANY, STAR_LEVEL, IS_INTERNAL)
SELECT '郭产品', '产品总监', '内部讲师', 4.0, 'Y' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TRAINERS WHERE TRAINER_NAME = '郭产品');

-- Courses (all DRAFT; S003 publishes the target course)
INSERT INTO TRAINING_COURSES (COURSE_NAME, COURSE_TYPE, DURATION_HOURS, TRAINER_ID, MAX_STUDENTS, START_AT, END_AT, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID)
SELECT '2026 微服务架构演进', '技术培训', 8.0,
       (SELECT TRAINER_ID FROM TRAINERS WHERE TRAINER_NAME = '陈技术'), 30,
       TO_TIMESTAMP('2026-08-10 09:00:00', 'YYYY-MM-DD HH24:MI:SS'),
       TO_TIMESTAMP('2026-08-10 18:00:00', 'YYYY-MM-DD HH24:MI:SS'),
       '总部第一会议室', 'DRAFT', 5000.00,
       (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '研发部')
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TRAINING_COURSES WHERE COURSE_NAME = '2026 微服务架构演进');

INSERT INTO TRAINING_COURSES (COURSE_NAME, COURSE_TYPE, DURATION_HOURS, TRAINER_ID, MAX_STUDENTS, START_AT, END_AT, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID)
SELECT 'C# Web API 最佳实践', '技术培训', 4.0,
       (SELECT TRAINER_ID FROM TRAINERS WHERE TRAINER_NAME = '陈技术'), 40,
       TO_TIMESTAMP('2026-08-15 13:00:00', 'YYYY-MM-DD HH24:MI:SS'),
       TO_TIMESTAMP('2026-08-15 17:00:00', 'YYYY-MM-DD HH24:MI:SS'),
       '总部第二会议室', 'DRAFT', 2000.00,
       (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '研发部')
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TRAINING_COURSES WHERE COURSE_NAME = 'C# Web API 最佳实践');

INSERT INTO TRAINING_COURSES (COURSE_NAME, COURSE_TYPE, DURATION_HOURS, TRAINER_ID, MAX_STUDENTS, START_AT, END_AT, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID)
SELECT '2026 敏捷项目管理工作坊', '管理培训', 16.0,
       (SELECT TRAINER_ID FROM TRAINERS WHERE TRAINER_NAME = '林外聘'), 20,
       TO_TIMESTAMP('2026-09-01 09:00:00', 'YYYY-MM-DD HH24:MI:SS'),
       TO_TIMESTAMP('2026-09-02 18:00:00', 'YYYY-MM-DD HH24:MI:SS'),
       '外部培训中心', 'DRAFT', 25000.00,
       (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '研发部')
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TRAINING_COURSES WHERE COURSE_NAME = '2026 敏捷项目管理工作坊');

INSERT INTO TRAINING_COURSES (COURSE_NAME, COURSE_TYPE, DURATION_HOURS, TRAINER_ID, MAX_STUDENTS, START_AT, END_AT, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID)
SELECT '用户体验驱动的产品设计', '产品培训', 6.0,
       (SELECT TRAINER_ID FROM TRAINERS WHERE TRAINER_NAME = '郭产品'), 25,
       TO_TIMESTAMP('2026-09-20 10:00:00', 'YYYY-MM-DD HH24:MI:SS'),
       TO_TIMESTAMP('2026-09-20 17:00:00', 'YYYY-MM-DD HH24:MI:SS'),
       '总部第三会议室', 'DRAFT', 3000.00,
       (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '产品部')
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TRAINING_COURSES WHERE COURSE_NAME = '用户体验驱动的产品设计');

INSERT INTO TRAINING_COURSES (COURSE_NAME, COURSE_TYPE, DURATION_HOURS, TRAINER_ID, MAX_STUDENTS, START_AT, END_AT, LOCATION, COURSE_STATUS, BUDGET_AMOUNT, DEPT_ID)
SELECT '2026 B2B 销售实战技巧', '营销培训', 12.0,
       (SELECT TRAINER_ID FROM TRAINERS WHERE TRAINER_NAME = '林外聘'), 50,
       TO_TIMESTAMP('2026-10-10 09:00:00', 'YYYY-MM-DD HH24:MI:SS'),
       TO_TIMESTAMP('2026-10-11 12:00:00', 'YYYY-MM-DD HH24:MI:SS'),
       '公司大会堂', 'DRAFT', 15000.00,
       (SELECT DEPT_ID FROM DEPARTMENTS_TRAINING WHERE DEPT_NAME = '市场部')
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM TRAINING_COURSES WHERE COURSE_NAME = '2026 B2B 销售实战技巧');

COMMIT;

