-- =========================================================================
-- Use Case: S003 Full Demo Business Flow History
-- Author: 钮培源
-- Date: 2026-07-20 (revised)
-- Is Repeatable: Yes
-- =========================================================================

WHENEVER SQLERROR EXIT FAILURE ROLLBACK
ALTER SESSION SET NLS_LENGTH_SEMANTICS = CHAR;

-- Publish the target course (DRAFT -> PUBLISHED)
UPDATE TRAINING_COURSES
SET COURSE_STATUS = 'PUBLISHED', UPDATED_AT = SYSTIMESTAMP
WHERE COURSE_NAME = 'C# Web API 最佳实践' AND COURSE_STATUS = 'DRAFT';

-- Sync department USED_BUDGET from PUBLISHED course budgets
MERGE INTO DEPARTMENTS_TRAINING d
USING (
    SELECT DEPT_ID, SUM(BUDGET_AMOUNT) AS TOTAL_USED
    FROM TRAINING_COURSES
    WHERE COURSE_STATUS = 'PUBLISHED'
    GROUP BY DEPT_ID
) src
ON (d.DEPT_ID = src.DEPT_ID)
WHEN MATCHED THEN
    UPDATE SET d.USED_BUDGET = src.TOTAL_USED,
               d.UPDATED_AT  = SYSTIMESTAMP;

-- Training request: dept-approved by rdmgr, HR-filed
INSERT INTO TRAINING_REQUESTS (
    EMP_ID, COURSE_ID, REASON, STATUS,
    DEPT_APPROVER_EMP_ID, DEPT_APPROVED_AT, HR_FILER_EMP_ID, HR_FILED_AT, REQUESTED_AT)
SELECT e.EMP_ID, c.COURSE_ID,
       '项目组即将全线转入 .NET 8，需要补充 API 架构知识', 'HR_FILED',
       mgr.EMP_ID, c.START_AT - INTERVAL '14' DAY,
       hr.EMP_ID,  c.START_AT - INTERVAL '13' DAY,
       c.START_AT - INTERVAL '15' DAY
FROM EMPLOYEES e
CROSS JOIN TRAINING_COURSES c
CROSS JOIN EMPLOYEES mgr
CROSS JOIN EMPLOYEES hr
WHERE e.LOGIN_NAME = 'dev01'
  AND c.COURSE_NAME = 'C# Web API 最佳实践'
  AND mgr.LOGIN_NAME = 'rdmgr'
  AND hr.LOGIN_NAME = 'hr'
  AND NOT EXISTS (SELECT 1 FROM TRAINING_REQUESTS req
                  WHERE req.EMP_ID = e.EMP_ID AND req.COURSE_ID = c.COURSE_ID);

-- Registration derived from the filed request; COMPLETED
--    ACTUAL_HOURS = DURATION_HOURS (on-time sign-in, no deduction).

INSERT INTO TRAINING_REGISTRATIONS (
    REQUEST_ID, EMP_ID, COURSE_ID, STATUS, REGISTERED_AT, COMPLETED_AT, ACTUAL_HOURS)
SELECT r.REQUEST_ID, r.EMP_ID, r.COURSE_ID, 'COMPLETED',
       c.START_AT - INTERVAL '10' DAY, c.END_AT, c.DURATION_HOURS
FROM TRAINING_REQUESTS r
JOIN EMPLOYEES e        ON r.EMP_ID = e.EMP_ID
JOIN TRAINING_COURSES c ON r.COURSE_ID = c.COURSE_ID
WHERE e.LOGIN_NAME = 'dev01' AND c.COURSE_NAME = 'C# Web API 最佳实践'
  AND NOT EXISTS (SELECT 1 FROM TRAINING_REGISTRATIONS reg
                  WHERE reg.EMP_ID = r.EMP_ID AND reg.COURSE_ID = r.COURSE_ID
                    AND reg.STATUS <> 'CANCELED');

-- Attendance (on time; signed in 10 minutes before START_AT)
INSERT INTO TRAINING_ATTENDANCE (
    REG_ID, SIGNIN_TYPE, SIGNED_IN_AT, LATENESS_MINUTES, DEDUCT_HOURS)
SELECT reg.REG_ID, 'SCAN', c.START_AT - INTERVAL '10' MINUTE, 0, 0.0
FROM TRAINING_REGISTRATIONS reg
JOIN TRAINING_COURSES c ON reg.COURSE_ID = c.COURSE_ID
JOIN EMPLOYEES e        ON reg.EMP_ID = e.EMP_ID
WHERE e.LOGIN_NAME = 'dev01' AND c.COURSE_NAME = 'C# Web API 最佳实践'
  AND NOT EXISTS (SELECT 1 FROM TRAINING_ATTENDANCE att WHERE att.REG_ID = reg.REG_ID);

-- Trainer rating, HR-verified (RATED_AT anchored to END_AT)
INSERT INTO TRAINER_RATINGS (
    COURSE_ID, TRAINER_ID, EMP_ID, SCORE, RATING_COMMENT,
    HR_VERIFIED, HR_VERIFIER_EMP_ID, VERIFIED_AT, RATED_AT)
SELECT c.COURSE_ID, c.TRAINER_ID, e.EMP_ID, 5.0,
       '陈老师讲解非常透彻，代码规范很受用。', 'Y', hr.EMP_ID, c.END_AT + INTERVAL '1' DAY, c.END_AT
FROM TRAINING_COURSES c
CROSS JOIN EMPLOYEES e
CROSS JOIN EMPLOYEES hr
WHERE e.LOGIN_NAME = 'dev01' AND c.COURSE_NAME = 'C# Web API 最佳实践' AND hr.LOGIN_NAME = 'hr'
  AND NOT EXISTS (SELECT 1 FROM TRAINER_RATINGS tr
                  WHERE tr.EMP_ID = e.EMP_ID AND tr.COURSE_ID = c.COURSE_ID);

-- Pre / post tests (PRE before START_AT, POST after END_AT)
INSERT INTO TRAINING_TESTS (EMP_ID, COURSE_ID, TEST_TYPE, SCORE, RECORDED_BY_EMP_ID, TESTED_AT)
SELECT e.EMP_ID, c.COURSE_ID, 'PRE', 65.0, hr.EMP_ID, c.START_AT - INTERVAL '1' HOUR
FROM EMPLOYEES e CROSS JOIN TRAINING_COURSES c CROSS JOIN EMPLOYEES hr
WHERE e.LOGIN_NAME = 'dev01' AND c.COURSE_NAME = 'C# Web API 最佳实践' AND hr.LOGIN_NAME = 'hr'
  AND NOT EXISTS (SELECT 1 FROM TRAINING_TESTS tt
                  WHERE tt.EMP_ID = e.EMP_ID AND tt.COURSE_ID = c.COURSE_ID AND tt.TEST_TYPE = 'PRE');

INSERT INTO TRAINING_TESTS (EMP_ID, COURSE_ID, TEST_TYPE, SCORE, RECORDED_BY_EMP_ID, TESTED_AT)
SELECT e.EMP_ID, c.COURSE_ID, 'POST', 95.5, hr.EMP_ID, c.END_AT + INTERVAL '1' HOUR
FROM EMPLOYEES e CROSS JOIN TRAINING_COURSES c CROSS JOIN EMPLOYEES hr
WHERE e.LOGIN_NAME = 'dev01' AND c.COURSE_NAME = 'C# Web API 最佳实践' AND hr.LOGIN_NAME = 'hr'
  AND NOT EXISTS (SELECT 1 FROM TRAINING_TESTS tt
                  WHERE tt.EMP_ID = e.EMP_ID AND tt.COURSE_ID = c.COURSE_ID AND tt.TEST_TYPE = 'POST');

-- Certificate (issued 2 days after END_AT)
INSERT INTO TRAINING_CERTIFICATES (
    EMP_ID, COURSE_ID, CERT_CODE, ISSUE_DATE, NOTIFIED, ISSUED_BY_EMP_ID)
SELECT e.EMP_ID, c.COURSE_ID,
       'CERT-' || TO_CHAR(c.END_AT, 'YYYYMMDD') || '-' || c.COURSE_ID || '-' || e.EMP_ID,
       TRUNC(CAST(c.END_AT + INTERVAL '2' DAY AS DATE)), 'N', hr.EMP_ID
FROM EMPLOYEES e CROSS JOIN TRAINING_COURSES c CROSS JOIN EMPLOYEES hr
WHERE e.LOGIN_NAME = 'dev01' AND c.COURSE_NAME = 'C# Web API 最佳实践' AND hr.LOGIN_NAME = 'hr'
  AND NOT EXISTS (SELECT 1 FROM TRAINING_CERTIFICATES tc
                  WHERE tc.EMP_ID = e.EMP_ID AND tc.COURSE_ID = c.COURSE_ID);

COMMIT;
