-- =========================================================================
-- Use Case: S003 Full Demo Business Flow History
-- Author: 钮培源
-- Date: 2026-07-17
-- =========================================================================

-- Publish target course (Prerequisite for valid application logic)
UPDATE TRAINING_COURSES
SET COURSE_STATUS = 'PUBLISHED', UPDATED_AT = SYSTIMESTAMP
WHERE COURSE_NAME = 'C# Web API 最佳实践';

-- Insert Training Request, simulating HR_FILED status
INSERT INTO TRAINING_REQUESTS (EMP_ID, COURSE_ID, REASON, STATUS, DEPT_APPROVER_EMP_ID, DEPT_APPROVED_AT, HR_FILER_EMP_ID, HR_FILED_AT)
SELECT 
    e.EMP_ID, 
    c.COURSE_ID, 
    '项目组即将全线转入 .NET 8，需要补充 API 架构知识', 
    'HR_FILED', 
    mgr.EMP_ID, 
    SYSTIMESTAMP - INTERVAL '10' DAY, 
    hr.EMP_ID, 
    SYSTIMESTAMP - INTERVAL '9' DAY
FROM EMPLOYEES e
CROSS JOIN TRAINING_COURSES c
CROSS JOIN EMPLOYEES mgr
CROSS JOIN EMPLOYEES hr
WHERE e.LOGIN_NAME = 'dev01' 
  AND c.COURSE_NAME = 'C# Web API 最佳实践' 
  AND mgr.LOGIN_NAME = 'manager' 
  AND hr.LOGIN_NAME = 'hr';

INSERT INTO TRAINING_REGISTRATIONS (REQUEST_ID, EMP_ID, COURSE_ID, STATUS, REGISTERED_AT, COMPLETED_AT, ACTUAL_HOURS)
SELECT 
    r.REQUEST_ID, 
    r.EMP_ID, 
    r.COURSE_ID, 
    'COMPLETED', 
    SYSTIMESTAMP - INTERVAL '8' DAY, 
    SYSTIMESTAMP - INTERVAL '2' DAY, 
    4.0
FROM TRAINING_REQUESTS r
JOIN EMPLOYEES e ON r.EMP_ID = e.EMP_ID
JOIN TRAINING_COURSES c ON r.COURSE_ID = c.COURSE_ID
WHERE e.LOGIN_NAME = 'dev01' AND c.COURSE_NAME = 'C# Web API 最佳实践';

INSERT INTO TRAINING_ATTENDANCE (REG_ID, SIGNIN_TYPE, SIGNED_IN_AT, LATENESS_MINUTES, DEDUCT_HOURS)
SELECT 
    reg.REG_ID, 
    'SCAN', 
    c.START_AT - INTERVAL '10' MINUTE, 
    0, 
    0.0
FROM TRAINING_REGISTRATIONS reg
JOIN TRAINING_COURSES c ON reg.COURSE_ID = c.COURSE_ID
JOIN EMPLOYEES e ON reg.EMP_ID = e.EMP_ID
WHERE e.LOGIN_NAME = 'dev01' AND c.COURSE_NAME = 'C# Web API 最佳实践';

-- This is verified by HR.
INSERT INTO TRAINER_RATINGS (COURSE_ID, TRAINER_ID, EMP_ID, SCORE, RATING_COMMENT, HR_VERIFIED, HR_VERIFIER_EMP_ID, VERIFIED_AT)
SELECT 
    c.COURSE_ID, 
    c.TRAINER_ID, 
    e.EMP_ID, 
    5.0, 
    '陈老师讲解非常透彻，代码规范很受用。', 
    'Y', 
    hr.EMP_ID, 
    SYSTIMESTAMP - INTERVAL '1' DAY
FROM TRAINING_COURSES c
CROSS JOIN EMPLOYEES e
CROSS JOIN EMPLOYEES hr
WHERE e.LOGIN_NAME = 'dev01' 
  AND c.COURSE_NAME = 'C# Web API 最佳实践' 
  AND hr.LOGIN_NAME = 'hr';

-- Insert training test Scores (Pre-test and Post-test)
INSERT INTO TRAINING_TESTS (EMP_ID, COURSE_ID, TEST_TYPE, SCORE, RECORDED_BY_EMP_ID)
SELECT e.EMP_ID, c.COURSE_ID, 'PRE', 65.0, hr.EMP_ID
FROM EMPLOYEES e, TRAINING_COURSES c, EMPLOYEES hr
WHERE e.LOGIN_NAME = 'dev01' AND c.COURSE_NAME = 'C# Web API 最佳实践' AND hr.LOGIN_NAME = 'hr';

INSERT INTO TRAINING_TESTS (EMP_ID, COURSE_ID, TEST_TYPE, SCORE, RECORDED_BY_EMP_ID)
SELECT e.EMP_ID, c.COURSE_ID, 'POST', 95.5, hr.EMP_ID
FROM EMPLOYEES e, TRAINING_COURSES c, EMPLOYEES hr
WHERE e.LOGIN_NAME = 'dev01' AND c.COURSE_NAME = 'C# Web API 最佳实践' AND hr.LOGIN_NAME = 'hr';

-- Insert final certificate
INSERT INTO TRAINING_CERTIFICATES (EMP_ID, COURSE_ID, CERT_CODE, ISSUE_DATE, NOTIFIED, ISSUED_BY_EMP_ID)
SELECT 
    e.EMP_ID, 
    c.COURSE_ID, 
    'CERT-20260815-' || c.COURSE_ID || '-' || e.EMP_ID, 
    TRUNC(SYSDATE), 
    'N', 
    hr.EMP_ID
FROM EMPLOYEES e
CROSS JOIN TRAINING_COURSES c
CROSS JOIN EMPLOYEES hr
WHERE e.LOGIN_NAME = 'dev01' 
  AND c.COURSE_NAME = 'C# Web API 最佳实践' 
  AND hr.LOGIN_NAME = 'hr';

COMMIT;
