<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import AppButton from '@/components/common/AppButton.vue'
import AppPagination from '@/components/common/AppPagination.vue'
import DataTable from '@/components/common/DataTable.vue'
import FormField from '@/components/common/FormField.vue'
import PageHeader from '@/components/common/PageHeader.vue'
import PageState from '@/components/common/PageState.vue'
import SearchPanel from '@/components/common/SearchPanel.vue'
import StatusTag from '@/components/common/StatusTag.vue'
import { getTrainerService } from '@/services/trainer'
import { isServiceError, type UiError } from '@/types/api'
import type { Trainer } from '@/domains/trainer'
import type { TableColumn } from '@/types/ui'

const filters = reactive({ name: '', company: '', internal: '' as '' | 'Y' | 'N', page: 1, pageSize: 20 })
const records = ref<Trainer[]>([]); const total = ref(0); const loading = ref(false); const loaded = ref(false); const error = ref<UiError | null>(null)
const creating = ref(false); const editing = ref<Trainer | null>(null); const saving = ref(false); const formError = ref('')
const form = reactive({ name: '', title: '', company: '', phone: '', email: '', starLevel: 3, isInternal: true })
const columns: TableColumn[] = [{ key: 'id', label: '编号', width: 90 }, { key: 'name', label: '讲师姓名', width: 120 }, { key: 'title', label: '职称', width: 150 }, { key: 'company', label: '单位/部门', minWidth: 160 }, { key: 'starLevel', label: '星级', width: 150 }, { key: 'isInternal', label: '类型', width: 100, align: 'center' }]
const state = computed(() => loading.value && !loaded.value ? 'loading' : error.value ? 'error' : records.value.length ? 'default' : 'empty')
const dialogVisible = computed({ get: () => creating.value || editing.value !== null, set: (value: boolean) => { if (!value && !saving.value) { creating.value = false; editing.value = null } } })
const dialogTitle = computed(() => creating.value ? '新增讲师' : '编辑讲师')
async function load() { loading.value = true; error.value = null; try { const result = await (await getTrainerService()).list({ name: filters.name || undefined, company: filters.company || undefined, internal: filters.internal || undefined, page: filters.page, pageSize: filters.pageSize }); records.value = result.items; total.value = result.total; loaded.value = true } catch (caught) { error.value = isServiceError(caught) ? caught.ui : { kind: 'unknown', code: 'UNKNOWN', message: '讲师数据加载失败。', fieldErrors: [], retryable: false, resultUnknown: false }; loaded.value = true } finally { loading.value = false } }
async function sync(next: Partial<typeof filters>, reset = false) { Object.assign(filters, next); if (reset) filters.page = 1; await load() }
function openCreate() { formError.value = ''; Object.assign(form, { name: '', title: '', company: '', phone: '', email: '', starLevel: 3, isInternal: true }); creating.value = true }
function openEdit(record: Trainer) { formError.value = ''; Object.assign(form, { name: record.name, title: record.title ?? '', company: record.company ?? '', phone: record.phone ?? '', email: record.email ?? '', starLevel: record.starLevel, isInternal: record.isInternal }); editing.value = record }
async function save() { if (!form.name.trim()) { formError.value = '请填写讲师姓名。'; return }; if (form.starLevel < 1 || form.starLevel > 5) { formError.value = '讲师星级必须在 1 至 5 之间。'; return }; saving.value = true; formError.value = ''; try { const service = await getTrainerService(); const input = { ...form, name: form.name.trim() }; if (creating.value) await service.create(input); else if (editing.value) await service.update(editing.value.id, input); creating.value = false; editing.value = null; await load() } catch (caught) { formError.value = isServiceError(caught) ? caught.ui.message : '保存讲师信息失败。' } finally { saving.value = false } }
onMounted(load)
</script>

<template><section class="trainer-management"><PageHeader title="讲师管理" description="维护内部与外部讲师资料，供课程创建和评分使用。"><template #action><AppButton label="新增讲师" variant="primary" @click="openCreate" /></template></PageHeader><SearchPanel :expanded="true" :searching="loading" @search="sync({}, true)" @reset="sync({ name: '', company: '', internal: '', page: 1 }, true)"><el-input v-model="filters.name" clearable placeholder="讲师姓名" aria-label="讲师姓名" /><el-input v-model="filters.company" clearable placeholder="单位或部门" aria-label="讲师单位" /><el-select v-model="filters.internal" clearable placeholder="讲师类型" aria-label="讲师类型"><el-option label="内部讲师" value="Y" /><el-option label="外部讲师" value="N" /></el-select></SearchPanel><PageState v-if="state === 'loading'" state="loading" /><PageState v-else-if="error" state="error" :description="error.message" primary-label="重新加载" @primary="load" /><PageState v-else-if="state === 'empty'" state="empty" title="暂无讲师" compact /><template v-else><DataTable :columns="columns" :rows="records" has-actions><template #cell="{ column, row }"><span v-if="column.key === 'starLevel'"><el-rate :model-value="Number(row.starLevel)" disabled allow-half /> {{ Number(row.starLevel).toFixed(1) }}</span><StatusTag v-else-if="column.key === 'isInternal'" :label="row.isInternal ? '内部' : '外部'" :semantic="row.isInternal ? 'success' : 'info'" /><span v-else>{{ row[column.key] || '—' }}</span></template><template #actions="{ row }"><AppButton label="编辑" variant="text" @click="openEdit(row as Trainer)" /></template></DataTable><AppPagination v-if="total" :page="filters.page" :page-size="filters.pageSize" :total="total" :disabled="loading" @update:page="sync({ page: $event })" @update:page-size="sync({ pageSize: $event }, true)" /></template><el-dialog v-model="dialogVisible" :title="dialogTitle" width="560px" :close-on-click-modal="!saving"><el-alert v-if="formError" :title="formError" type="error" show-icon :closable="false" /><el-form label-position="top"><FormField label="讲师姓名" required><el-input v-model="form.name" maxlength="50" /></FormField><div class="grid"><FormField label="职称"><el-input v-model="form.title" maxlength="50" /></FormField><FormField label="单位/部门"><el-input v-model="form.company" maxlength="100" /></FormField></div><div class="grid"><FormField label="邮箱"><el-input v-model="form.email" /></FormField><FormField label="电话"><el-input v-model="form.phone" maxlength="20" /></FormField></div><div class="grid"><FormField label="讲师星级" required><el-rate v-model="form.starLevel" allow-half show-score /></FormField><FormField label="讲师类型" required><el-radio-group v-model="form.isInternal"><el-radio :value="true">内部讲师</el-radio><el-radio :value="false">外部讲师</el-radio></el-radio-group></FormField></div></el-form><template #footer><AppButton label="取消" :disabled="saving" @click="dialogVisible = false" /><AppButton label="保存" variant="primary" :loading="saving" @click="save" /></template></el-dialog></section></template>

<style scoped>.trainer-management{display:grid;gap:var(--space-6)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:var(--space-4)}</style>
