CREATE INDEX IDX_EMP_DEPT_STATUS ON EMPLOYEES (DEPT_ID, STATUS);
CREATE INDEX IDX_EMP_MANAGER ON EMPLOYEES (MANAGER_EMP_ID);
CREATE INDEX IDX_USER_ROLES_ROLE ON USER_ROLES (ROLE_ID);
CREATE INDEX IDX_BLACKLIST_EMP ON BLACKLIST (EMP_ID);
CREATE INDEX IDX_COURSES_TRAINER ON TRAINING_COURSES (TRAINER_ID);
CREATE INDEX IDX_COURSES_DEPT ON TRAINING_COURSES (DEPT_ID);
CREATE INDEX IDX_COURSES_STATUS_START ON TRAINING_COURSES (COURSE_STATUS, START_AT);
CREATE INDEX IDX_REQ_STATUS_COURSE ON TRAINING_REQUESTS (STATUS, COURSE_ID);
CREATE INDEX IDX_REQ_EMP_DATE ON TRAINING_REQUESTS (EMP_ID, REQUESTED_AT);
CREATE INDEX IDX_REQ_DEPT_APPROVER ON TRAINING_REQUESTS (DEPT_APPROVER_EMP_ID);
CREATE INDEX IDX_REQ_HR_FILER ON TRAINING_REQUESTS (HR_FILER_EMP_ID);
CREATE INDEX IDX_REG_COURSE_STATUS ON TRAINING_REGISTRATIONS (COURSE_ID, STATUS);
CREATE INDEX IDX_REG_EMP_DATE ON TRAINING_REGISTRATIONS (EMP_ID, REGISTERED_AT);
CREATE INDEX IDX_RATINGS_TRAINER ON TRAINER_RATINGS (TRAINER_ID, RATED_AT);
CREATE INDEX IDX_RATINGS_COURSE ON TRAINER_RATINGS (COURSE_ID);
CREATE INDEX IDX_RATINGS_VERIFIER ON TRAINER_RATINGS (HR_VERIFIER_EMP_ID);
CREATE INDEX IDX_TESTS_COURSE ON TRAINING_TESTS (COURSE_ID);
CREATE INDEX IDX_TESTS_RECORDER ON TRAINING_TESTS (RECORDED_BY_EMP_ID);
CREATE INDEX IDX_CERT_EMP_DATE ON TRAINING_CERTIFICATES (EMP_ID, ISSUE_DATE);
CREATE INDEX IDX_CERT_COURSE ON TRAINING_CERTIFICATES (COURSE_ID);
CREATE INDEX IDX_CERT_ISSUER ON TRAINING_CERTIFICATES (ISSUED_BY_EMP_ID);

CREATE UNIQUE INDEX UQ_BLACKLIST_ACTIVE_EMP ON BLACKLIST
    (CASE WHEN STATUS = 'ACTIVE' THEN EMP_ID END);

CREATE UNIQUE INDEX UQ_REQ_ACTIVE_EMP_COURSE ON TRAINING_REQUESTS
    (CASE WHEN STATUS IN ('PENDING', 'DEPT_APPROVED', 'HR_FILED') THEN EMP_ID END,
     CASE WHEN STATUS IN ('PENDING', 'DEPT_APPROVED', 'HR_FILED') THEN COURSE_ID END);

CREATE UNIQUE INDEX UQ_REG_ACTIVE_EMP_COURSE ON TRAINING_REGISTRATIONS
    (CASE WHEN STATUS <> 'CANCELED' THEN EMP_ID END,
     CASE WHEN STATUS <> 'CANCELED' THEN COURSE_ID END);