BEGIN
    FOR t IN (
        SELECT TABLE_NAME
        FROM USER_TABLES
        WHERE TABLE_NAME IN (
            'DEPARTMENTS_TRAINING', 'EMPLOYEES', 'ROLES', 'USER_ROLES',
            'BLACKLIST', 'TRAINERS', 'TRAINING_COURSES', 'TRAINING_REQUESTS',
            'TRAINING_REGISTRATIONS', 'TRAINING_ATTENDANCE', 'TRAINER_RATINGS',
            'TRAINING_TESTS', 'TRAINING_CERTIFICATES'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON '
            || DBMS_ASSERT.ENQUOTE_NAME(t.TABLE_NAME, FALSE)
            || ' TO TRAINING_APP';
    END LOOP;
END;
/