-- 黑名单记录补充操作人审计字段（操作人可空，兼容既有历史数据）。
ALTER TABLE BLACKLIST ADD OPERATOR_EMP_ID NUMBER;

ALTER TABLE BLACKLIST ADD CONSTRAINT FK_BLACKLIST_OPERATOR
    FOREIGN KEY (OPERATOR_EMP_ID) REFERENCES EMPLOYEES (EMP_ID);
